# Generated by Django 3.0.14 on 2023-06-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='url',
        ),
    ]
