# Generated by Django 3.0.14 on 2023-06-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230611_0200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Our_Media',
        ),
    ]
